### ISSUE TITLE
Upgrade the app to typescript

### ISSUE THREAD

**Issue by amosmachora** [omondi8399/CryptoLeo#12]
The app currently uses javascript. I was recommending upgrading to typescript to take advantage of features like LINT and code completion.

**Comment by omondi8399** [comment]
Yeah go ahead

**Comment by omondi8399** [comment]
> The app currently uses javascript. I was recommending upgrading to typescript to take advantage of features like LINT and code completion.

i approve

**Comment by JesusC-R** [comment]
I'd like to help. Would you please assign this task to me?

**Comment by omondi8399** [comment]
> I'd like to help. Would you please assign this task to me?

yeah sure .

**Comment by omondi8399** [comment]
Yeah you can

**Comment by adolfmathebula** [comment]
I have been waiting for you guys to upgrade the app to Typescript. What's the hold up?

**Comment by omondi8399** [comment]
> I have been waiting for you guys to upgrade the app to Typescript. What's the hold up?

someone is yet to work on it.

**Comment by amosmachora** [comment]
Im working on it. Planning to use a lot of any to get the ball rolling but we will figure out and add the actual types as we go.

**Comment by omondi8399** [comment]
> Im working on it. Planning to use a lot of any to get the ball rolling but we will figure out and add the actual types as we go.

tried fixing it , great job @amosmachora

**Comment by amosmachora** [comment]
@omondi8399 did the vercel deployment work?
