### ISSUE TITLE
Node modules failure

### ISSUE THREAD

**Issue by Mbhon1** [omondi8399/CryptoLeo#18]
Conflicting typescript packages won't allow me to install the necessary dependencies.

![2023-07-14-092525_hyprshot](https://github.com/omondi8399/CryptoLeo/assets/110413308/6fefc1bf-9199-44d6-b77f-6fbac989c3c2)

Production failed as well as preview.

**Comment by omondi8399** [comment]
use npm install --force

**Comment by Mbhon1** [comment]
I did but do you think that's a good thing for the project moving forward?? My humble opinion is that you migrate to Next.JS that way maintaining would be far simpler.

**Comment by omondi8399** [comment]
> I did but do you think that's a good thing for the project moving forward?? My humble opinion is that you migrate to Next.JS that way maintaining would be far simpler.

currently working to make sure this is fixed . one problem at a time

**Comment by Mbhon1** [comment]
Cool. I'll be submitting a refactoring PR later.
