### ISSUE TITLE
Trending component

### ISSUE THREAD

**Issue by Mbhon1** [omondi8399/CryptoLeo#2]
The trending component has a bug that renders the reset button to the full width of the screen, and the coin logos are overly sized. This make it difficult to interact with the page as I can't click on the coins in the trending list.

**Comment by omondi8399** [comment]
It's currently working well on desktop , i will work making it responsive and function properly , thanks for pointing that out.

**Comment by Mbhon1** [comment]
I tried to solve the reset button to a smaller size, this is the code 

```jsx
<svg
            xmlns="http://www.w3.org/2000/svg"
            // width="1em"
            // height="1em" // these create an overlapping side-scroll when hovering or clicking the button
            viewBox="0 0 24 24"
            className="w-[100%] h-[2em] fill-cyan mx-auto" // mx-auto to center the button, also changed the height so it doesn't render on the whole screen
            style={{
              msTransform: "rotate(360deg)",
              WebkitTransform: "rotate(360deg)",
              transform: "rotate(360deg)",
            }}
          >
```

Before
![2023-07-02-090427_hyprshot](https://github.com/omondi8399/CryptoLeo/assets/110413308/0c6efc33-b90b-4015-ad7e-a8ea1f9219fa)

After
![2023-07-02-110016_hyprshot](https://github.com/omondi8399/CryptoLeo/assets/110413308/f5d784fe-96b7-4216-addd-7b66e3cf568d)

Do you mind migrating your project to Next.js??

**Comment by omondi8399** [comment]
i just solved the issue check again , i don't mind ,  l love Nextjs.
