### ISSUE TITLE
Gradual Migration Recommended

### ISSUE THREAD

**Issue by adolfmathebula** [omondi8399/CryptoLeo#20]
From where I am sitting I feel like there is such a rush to migrate to typescript that it's starting to introduce issues. Is it possible for issues to be opened and assigned so we know who's doing what. Perhaps also get communication from anyone who is working on an issue as to when they are likely to finish? The latest git pull request I made is such an unprofessional mess.

**Comment by Mbhon1** [comment]
I opened the same issue, too many duplicating files that caused production to fail. I was working on refactoring and type declaration on a separate branch. Check latest PR.

**Comment by amosmachora** [comment]
Sorry for taking a while but the app has now been fully updated to typescript. Most of the types are any but we will add them as we go.

**Comment by adolfmathebula** [comment]
> Sorry for taking a while but the app has now been fully updated to typescript. Most of the types are any but we will add them as we go.

And you did such a good job.
